on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Quarto Book
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Pythia Book
        uses: actions/checkout@v4
        with:
          repository: tuw-geo/eo-datascience-cookbook
          path: eo-datascience-cookbook

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore Cache Jupyter Kernels
        id: cache-jupyter-kernels-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.local/share/jupyter/kernels
            /usr/share/miniconda/envs
          key: ${{ runner.os }}-jupyter-${{ hashFiles('chapters/*.yml') }}

      - name: Render and Publish
        id: setup-python
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Jupyter Kernels
        id: cache-jupyter-kernels-save
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.local/share/jupyter/kernels
            /usr/share/miniconda/envs
          key: ${{ steps.cache-jupyter-kernels-restore.outputs.cache-primary-key }}

      # - name: Cache Binder Build on mybinder.org
      #   uses: jupyterhub/repo2docker-action@master
      #   with:
      #     NO_PUSH: true
      #     MYBINDERORG_TAG: ${{ github.event.ref }} 
      #     REPO2DOCKER_EXTRA_ARGS: --subdir notebooks

      - name: Commit Files
        if: github.ref == 'refs/heads/main'
        run: |
          NB_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]ipynb$'))
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit ${NB_PATH[*]} -m "Quarto output" || echo "No changes to commit"

      - name: Push Commit
        if: github.ref == 'refs/heads/main'
        uses: ad-m/github-push-action@master
        with:
          directory: eo-datascience-cookbook
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true