on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        id: setup-python
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Jupyter Kernels
        uses: actions/cache@v3
        with:
          path: ~/.local/share/jupyter/kernels
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-jupyter-${{ hashFiles('chapters/*.yml') }}

      - name: Cache Binder Build on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }} 
          REPO2DOCKER_EXTRA_ARGS: --subdir notebooks
      - name: Commit Files
        if: github.ref == 'refs/heads/master'
        run: |
          git checkout pythia
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add notebooks/*.ipynb
          git commit -m "Quarto output"
      - name: Push commit
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pythia
          force: true