on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        run: make kernel

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cache binder build on mybinder.org
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }} 
          REPO2DOCKER_EXTRA_ARGS: [--sub-dir, pangeo-workflow-examples]